version: 1.2
workflows:
   -  name: Dipcall
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/dipcall.wdl
   -  name: BUSCO
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/busco.wdl
   -  name: Quast
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/quast.wdl
   -  name: Meryl
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/meryl.wdl
   -  name: Merqury
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/merqury.wdl
   -  name: Asmgene
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/asmgene.wdl
   -  name: YakAsmStats
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/yak.wdl
   -  name: YakAsmStatsnoQV
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/yak_no_qv.wdl
   -  name: Mash
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/mash.wdl
   -  name: GreatLengths
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/great_lengths.wdl
   -  name: FullQC
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/workflows/full_qc.wdl
   -  name: StandardQC
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/workflows/standard_qc.wdl
   -  name: StandardQCnoQV
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/workflows/standard_qc_no_qv.wdl
   -  name: TrioHifiasmAssembly
      subclass: WDL
      primaryDescriptorPath: /assembly/wdl/workflows/trio_hifiasm_assembly.wdl
   -  name: YakNoStats
      subclass: WDL
      primaryDescriptorPath: /assembly/wdl/tasks/yak_no_stats.wdl
   -  name: Bwa
      subclass: WDL
      primaryDescriptorPath: /asset/wdl/tasks/bwa.wdl
   -  name: LongReadAligner
      subclass: WDL
      primaryDescriptorPath: /asset/wdl/tasks/long_read_aligner.wdl
   -  name: Asset
      subclass: WDL
      primaryDescriptorPath: /asset/wdl/tasks/asset.wdl
   -  name: Bam2Paf
      subclass: WDL
      primaryDescriptorPath: /asset/wdl/tasks/bam2paf.wdl
   -  name: AssetBamInput
      subclass: WDL
      primaryDescriptorPath: /asset/wdl/workflows/asset_bam_input.wdl
   -  name: BionanoAlignment
      subclass: WDL
      primaryDescriptorPath: /asset/wdl/tasks/bionano.wdl
   -  name: FullAlignmentForAsset
      subclass: WDL
      primaryDescriptorPath: /asset/wdl/workflows/full_alignment_for_asset.wdl
   -  name: AssetMerge
      subclass: WDL
      primaryDescriptorPath: /asset/wdl/tasks/asset_merge.wdl
   -  name: Bed2Fasta
      subclass: WDL
      primaryDescriptorPath: /asset/wdl/tasks/bed2fasta.wdl
   -  name: Asm2AsmAligner
      subclass: WDL
      primaryDescriptorPath: /asset/wdl/tasks/asm2asm_aligner.wdl


